import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'bn' | 'te' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Auth
    'auth.welcome': 'Welcome to Smart Crop Advisory',
    'auth.signin_farmer': 'Sign in as Farmer',
    'auth.signin_merchant': 'Sign in as Merchant',
    'auth.signin_expert': 'Sign in as Expert',
    'auth.signin_admin': 'Sign in as Admin',
    'auth.farmer_desc': 'Manage crops, get AI recommendations, connect with merchants',
    'auth.merchant_desc': 'Connect with farmers, manage purchases, set crop prices',
    'auth.expert_desc': 'Provide advisory services, share agricultural expertise',
    'auth.admin_desc': 'Manage system, oversee all operations and users',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signin': 'Sign In',
    'auth.signup': 'Create Account',
    'auth.signin_desc': 'Enter your credentials to access your dashboard',
    'auth.signup_desc': 'Create a new account to get started',
    'auth.fullname': 'Full Name',
    'auth.role': 'Role',
    'auth.phone': 'Phone Number',
    'auth.location': 'Location',
    'auth.enter_email': 'Enter your email address',
    'auth.enter_password': 'Enter your password',
    'auth.enter_name': 'Enter your full name',
    'auth.enter_phone': 'Enter your phone number',
    'auth.enter_location': 'Enter your location',
    'auth.no_account': "Don't have an account? Sign up",
    'auth.have_account': 'Already have an account? Sign in',
    'auth.forgot_password': 'Forgot Password?',
    'auth.login_success': 'Welcome back!',
    'auth.logged_in_as': 'Logged in as',
    'auth.login_failed': 'Login Failed',
    'auth.invalid_credentials': 'Invalid email or password for this role. Please sign up first.',
    'auth.weak_password': 'Weak Password',
    'auth.password_min': 'Password must be at least 6 characters.',
    'auth.user_exists': 'User Exists',
    'auth.already_registered': 'This email is already registered for this role. Please sign in.',
    'auth.signup_success': 'Account Created!',
    'auth.now_login': 'You can now sign in with your credentials.',
    'auth.or_continue_with': 'Or continue with',
    'auth.google_signin': 'Sign in with Google',
    'auth.phone_signin': 'Sign in with Phone',
    'auth.terms': 'By continuing, you agree to our Terms of Service and Privacy Policy',
    // Common
    'common.select_language': 'Select Language',
    'common.continue': 'Continue',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.loading': 'Please wait...',
    'common.signout': 'Sign Out',
    'common.profile': 'Profile',
    'common.back': 'Back to role selection',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.active_crops': 'Active Crops',
    'dashboard.total_area': 'Total Area',
    'dashboard.active_sensors': 'Active Sensors',
    'dashboard.upcoming_tasks': 'Upcoming Tasks',
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.crops': 'My Crops',
    'nav.advisory': 'Advisory',
    'nav.weather': 'Weather',
    'nav.sensors': 'Sensors',
    'nav.fieldmap': 'Field Map',
    'nav.merchants': 'Merchants',
    'nav.polls': 'Polls',
    'nav.schemes': 'Gov Schemes',
    // Hero
    'hero.title': 'Smart Crop Advisory',
    'hero.subtitle': 'System',
    'hero.description': 'Revolutionize your farming with AI-powered recommendations, real-time monitoring, and expert guidance for optimal crop yields.',
    'hero.cta': 'Start Free Trial',
    'hero.demo': 'View Demo',
    // Features
    'features.title': 'Everything You Need for',
    'features.highlight': 'Smart Farming',
    'features.description': 'Comprehensive tools and insights to help you make data-driven decisions',
    // AI
    'ai.placeholder': 'Ask me about crops, weather, farming tips...',
    'ai.title': 'AI Farm Assistant',
    'ai.greeting': 'Namaste! 🙏 I\'m your AI farming assistant. Ask me anything about crops, weather, soil, or farming techniques!',
  },
  hi: {
    'auth.welcome': 'स्मार्ट क्रॉप एडवाइजरी में आपका स्वागत है',
    'auth.signin_farmer': 'किसान के रूप में साइन इन करें',
    'auth.signin_merchant': 'व्यापारी के रूप में साइन इन करें',
    'auth.signin_expert': 'विशेषज्ञ के रूप में साइन इन करें',
    'auth.signin_admin': 'प्रशासक के रूप में साइन इन करें',
    'auth.farmer_desc': 'फसलें प्रबंधित करें, AI सिफारिशें पाएं, व्यापारियों से जुड़ें',
    'auth.merchant_desc': 'किसानों से जुड़ें, खरीदारी प्रबंधित करें, फसल मूल्य तय करें',
    'auth.expert_desc': 'सलाहकार सेवाएं प्रदान करें, कृषि विशेषज्ञता साझा करें',
    'auth.admin_desc': 'सिस्टम प्रबंधित करें, सभी संचालन और उपयोगकर्ताओं की निगरानी करें',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.signin': 'साइन इन करें',
    'auth.signup': 'खाता बनाएं',
    'auth.signin_desc': 'अपने डैशबोर्ड तक पहुंचने के लिए अपनी जानकारी दर्ज करें',
    'auth.signup_desc': 'शुरू करने के लिए एक नया खाता बनाएं',
    'auth.fullname': 'पूरा नाम',
    'auth.role': 'भूमिका',
    'auth.phone': 'फोन नंबर',
    'auth.location': 'स्थान',
    'auth.enter_email': 'अपना ईमेल दर्ज करें',
    'auth.enter_password': 'अपना पासवर्ड दर्ज करें',
    'auth.enter_name': 'अपना पूरा नाम दर्ज करें',
    'auth.enter_phone': 'अपना फोन नंबर दर्ज करें',
    'auth.enter_location': 'अपना स्थान दर्ज करें',
    'auth.no_account': 'खाता नहीं है? साइन अप करें',
    'auth.have_account': 'पहले से खाता है? साइन इन करें',
    'auth.forgot_password': 'पासवर्ड भूल गए?',
    'auth.login_success': 'वापसी पर स्वागत है!',
    'auth.logged_in_as': 'इस रूप में लॉग इन',
    'auth.login_failed': 'लॉगिन विफल',
    'auth.invalid_credentials': 'इस भूमिका के लिए अमान्य ईमेल या पासवर्ड। कृपया पहले साइन अप करें।',
    'auth.weak_password': 'कमज़ोर पासवर्ड',
    'auth.password_min': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
    'auth.user_exists': 'उपयोगकर्ता मौजूद है',
    'auth.already_registered': 'यह ईमेल इस भूमिका के लिए पहले से पंजीकृत है। कृपया साइन इन करें।',
    'auth.signup_success': 'खाता बनाया गया!',
    'auth.now_login': 'अब आप अपनी जानकारी से साइन इन कर सकते हैं।',
    'auth.or_continue_with': 'या इसके साथ जारी रखें',
    'auth.google_signin': 'Google से साइन इन करें',
    'auth.phone_signin': 'फोन से साइन इन करें',
    'auth.terms': 'जारी रखकर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत हैं',
    'common.select_language': 'भाषा चुनें',
    'common.continue': 'जारी रखें',
    'common.cancel': 'रद्द करें',
    'common.save': 'सेव करें',
    'common.loading': 'कृपया प्रतीक्षा करें...',
    'common.signout': 'साइन आउट',
    'common.profile': 'प्रोफाइल',
    'common.back': 'भूमिका चयन पर वापस जाएं',
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.welcome': 'वापसी पर स्वागत है',
    'dashboard.active_crops': 'सक्रिय फसलें',
    'dashboard.total_area': 'कुल क्षेत्र',
    'dashboard.active_sensors': 'सक्रिय सेंसर',
    'dashboard.upcoming_tasks': 'आगामी कार्य',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.crops': 'मेरी फसलें',
    'nav.advisory': 'सलाह',
    'nav.weather': 'मौसम',
    'nav.sensors': 'सेंसर',
    'nav.fieldmap': 'खेत का नक्शा',
    'nav.merchants': 'व्यापारी',
    'nav.polls': 'मतदान',
    'nav.schemes': 'सरकारी योजनाएं',
    'hero.title': 'स्मार्ट क्रॉप एडवाइजरी',
    'hero.subtitle': 'सिस्टम',
    'hero.description': 'AI-संचालित सिफारिशों, रियल-टाइम मॉनिटरिंग, और विशेषज्ञ मार्गदर्शन के साथ अपनी खेती में क्रांति लाएं।',
    'hero.cta': 'मुफ्त शुरू करें',
    'hero.demo': 'डेमो देखें',
    'features.title': 'स्मार्ट खेती के लिए',
    'features.highlight': 'सब कुछ',
    'features.description': 'डेटा-आधारित निर्णय लेने में मदद करने के लिए व्यापक उपकरण और अंतर्दृष्टि',
    'ai.placeholder': 'फसलों, मौसम, खेती की टिप्स के बारे में पूछें...',
    'ai.title': 'AI कृषि सहायक',
    'ai.greeting': 'नमस्ते! 🙏 मैं आपका AI कृषि सहायक हूं। फसलों, मौसम, मिट्टी, या खेती की तकनीकों के बारे में कुछ भी पूछें!',
  },
  bn: {
    'auth.welcome': 'স্মার্ট ক্রপ অ্যাডভাইজরিতে স্বাগতম',
    'auth.signin_farmer': 'কৃষক হিসেবে সাইন ইন করুন',
    'auth.signin_merchant': 'ব্যবসায়ী হিসেবে সাইন ইন করুন',
    'auth.signin_expert': 'বিশেষজ্ঞ হিসেবে সাইন ইন করুন',
    'auth.signin_admin': 'প্রশাসক হিসেবে সাইন ইন করুন',
    'auth.farmer_desc': 'ফসল পরিচালনা করুন, AI সুপারিশ পান, ব্যবসায়ীদের সাথে যুক্ত হন',
    'auth.merchant_desc': 'কৃষকদের সাথে যুক্ত হন, ক্রয় পরিচালনা করুন, ফসলের দাম নির্ধারণ করুন',
    'auth.expert_desc': 'পরামর্শ সেবা প্রদান করুন, কৃষি দক্ষতা শেয়ার করুন',
    'auth.admin_desc': 'সিস্টেম পরিচালনা করুন, সমস্ত কার্যক্রম ও ব্যবহারকারীদের তদারকি করুন',
    'auth.email': 'ইমেইল',
    'auth.password': 'পাসওয়ার্ড',
    'auth.signin': 'সাইন ইন',
    'auth.signup': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.signin_desc': 'আপনার ড্যাশবোর্ডে প্রবেশ করতে আপনার তথ্য দিন',
    'auth.signup_desc': 'শুরু করতে একটি নতুন অ্যাকাউন্ট তৈরি করুন',
    'auth.fullname': 'পূর্ণ নাম',
    'auth.role': 'ভূমিকা',
    'auth.phone': 'ফোন নম্বর',
    'auth.location': 'অবস্থান',
    'auth.enter_email': 'আপনার ইমেইল দিন',
    'auth.enter_password': 'আপনার পাসওয়ার্ড দিন',
    'auth.enter_name': 'আপনার পূর্ণ নাম দিন',
    'auth.enter_phone': 'আপনার ফোন নম্বর দিন',
    'auth.enter_location': 'আপনার অবস্থান দিন',
    'auth.no_account': 'অ্যাকাউন্ট নেই? সাইন আপ করুন',
    'auth.have_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে? সাইন ইন করুন',
    'auth.forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.login_success': 'ফিরে আসার জন্য স্বাগতম!',
    'auth.logged_in_as': 'লগইন হয়েছে',
    'auth.login_failed': 'লগইন ব্যর্থ',
    'auth.invalid_credentials': 'এই ভূমিকার জন্য অবৈধ ইমেইল বা পাসওয়ার্ড। প্রথমে সাইন আপ করুন।',
    'auth.weak_password': 'দুর্বল পাসওয়ার্ড',
    'auth.password_min': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
    'auth.user_exists': 'ব্যবহারকারী বিদ্যমান',
    'auth.already_registered': 'এই ইমেইল এই ভূমিকার জন্য ইতিমধ্যে নিবন্ধিত। সাইন ইন করুন।',
    'auth.signup_success': 'অ্যাকাউন্ট তৈরি হয়েছে!',
    'auth.now_login': 'এখন আপনি আপনার তথ্য দিয়ে সাইন ইন করতে পারেন।',
    'auth.or_continue_with': 'অথবা এর সাথে চালিয়ে যান',
    'auth.google_signin': 'Google দিয়ে সাইন ইন',
    'auth.phone_signin': 'ফোন দিয়ে সাইন ইন',
    'auth.terms': 'চালিয়ে যাওয়ার মাধ্যমে, আপনি আমাদের সেবার শর্তাবলী এবং গোপনীয়তা নীতিতে সম্মত হচ্ছেন',
    'common.select_language': 'ভাষা নির্বাচন করুন',
    'common.continue': 'অব্যাহত',
    'common.cancel': 'বাতিল',
    'common.save': 'সেভ',
    'common.loading': 'অপেক্ষা করুন...',
    'common.signout': 'সাইন আউট',
    'common.profile': 'প্রোফাইল',
    'common.back': 'ভূমিকা নির্বাচনে ফিরে যান',
    'dashboard.title': 'ড্যাশবোর্ড',
    'dashboard.welcome': 'ফিরে আসার জন্য স্বাগতম',
    'dashboard.active_crops': 'সক্রিয় ফসল',
    'dashboard.total_area': 'মোট এলাকা',
    'dashboard.active_sensors': 'সক্রিয় সেন্সর',
    'dashboard.upcoming_tasks': 'আসন্ন কাজ',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.crops': 'আমার ফসল',
    'nav.advisory': 'পরামর্শ',
    'nav.weather': 'আবহাওয়া',
    'nav.sensors': 'সেন্সর',
    'nav.fieldmap': 'মাঠের মানচিত্র',
    'nav.merchants': 'ব্যবসায়ী',
    'nav.polls': 'ভোট',
    'nav.schemes': 'সরকারি প্রকল্প',
    'hero.title': 'স্মার্ট ক্রপ অ্যাডভাইজরি',
    'hero.subtitle': 'সিস্টেম',
    'hero.description': 'AI-চালিত সুপারিশ, রিয়েল-টাইম মনিটরিং, এবং বিশেষজ্ঞ নির্দেশনা দিয়ে আপনার চাষে বিপ্লব আনুন।',
    'hero.cta': 'বিনামূল্যে শুরু করুন',
    'hero.demo': 'ডেমো দেখুন',
    'features.title': 'স্মার্ট চাষের জন্য',
    'features.highlight': 'সবকিছু',
    'features.description': 'ডেটা-চালিত সিদ্ধান্ত নিতে সাহায্য করার জন্য ব্যাপক সরঞ্জাম এবং অন্তর্দৃষ্টি',
    'ai.placeholder': 'ফসল, আবহাওয়া, চাষের টিপস সম্পর্কে জিজ্ঞাসা করুন...',
    'ai.title': 'AI কৃষি সহায়ক',
    'ai.greeting': 'নমস্কার! 🙏 আমি আপনার AI কৃষি সহায়ক। ফসল, আবহাওয়া, মাটি, বা চাষ কৌশল সম্পর্কে যেকোনো প্রশ্ন করুন!',
  },
  te: {
    'auth.welcome': 'స్మార్ట్ క్రాప్ అడ్వైజరీకి స్వాగతం',
    'auth.signin_farmer': 'రైతుగా సైన్ ఇన్ చేయండి',
    'auth.signin_merchant': 'వ్యాపారిగా సైన్ ఇన్ చేయండి',
    'auth.signin_expert': 'నిపుణుడిగా సైన్ ఇన్ చేయండి',
    'auth.signin_admin': 'నిర్వాహకుడిగా సైన్ ఇన్ చేయండి',
    'auth.farmer_desc': 'పంటలను నిర్వహించండి, AI సిఫార్సులు పొందండి, వ్యాపారులతో అనుసంధానం చేయండి',
    'auth.merchant_desc': 'రైతులతో అనుసంధానం చేయండి, కొనుగోళ్లను నిర్వహించండి, పంట ధరలు నిర్ణయించండి',
    'auth.expert_desc': 'సలహా సేవలు అందించండి, వ్యవసాయ నైపుణ్యాన్ని పంచుకోండి',
    'auth.admin_desc': 'సిస్టమ్ నిర్వహించండి, అన్ని కార్యకలాపాలు మరియు వినియోగదారులను పర్యవేక్షించండి',
    'auth.email': 'ఇమెయిల్',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.signin': 'సైన్ ఇన్',
    'auth.signup': 'ఖాతా సృష్టించండి',
    'auth.signin_desc': 'మీ డ్యాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి మీ వివరాలు నమోదు చేయండి',
    'auth.signup_desc': 'ప్రారంభించడానికి కొత్త ఖాతా సృష్టించండి',
    'auth.fullname': 'పూర్తి పేరు',
    'auth.role': 'పాత్ర',
    'auth.phone': 'ఫోన్ నంబర్',
    'auth.location': 'స్థానం',
    'auth.enter_email': 'మీ ఇమెయిల్ నమోదు చేయండి',
    'auth.enter_password': 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    'auth.enter_name': 'మీ పూర్తి పేరు నమోదు చేయండి',
    'auth.enter_phone': 'మీ ఫోన్ నంబర్ నమోదు చేయండి',
    'auth.enter_location': 'మీ స్థానం నమోదు చేయండి',
    'auth.no_account': 'ఖాతా లేదా? సైన్ అప్ చేయండి',
    'auth.have_account': 'ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి',
    'auth.forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
    'auth.login_success': 'తిరిగి రావడానికి స్వాగతం!',
    'auth.logged_in_as': 'లాగిన్ అయ్యారు',
    'auth.login_failed': 'లాగిన్ విఫలమైంది',
    'auth.invalid_credentials': 'ఈ పాత్ర కోసం చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్. దయచేసి ముందు సైన్ అప్ చేయండి.',
    'auth.weak_password': 'బలహీన పాస్‌వర్డ్',
    'auth.password_min': 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.',
    'auth.user_exists': 'వినియోగదారుడు ఉన్నారు',
    'auth.already_registered': 'ఈ ఇమెయిల్ ఈ పాత్ర కోసం ఇప్పటికే నమోదు చేయబడింది. దయచేసి సైన్ ఇన్ చేయండి.',
    'auth.signup_success': 'ఖాతా సృష్టించబడింది!',
    'auth.now_login': 'ఇప్పుడు మీరు మీ వివరాలతో సైన్ ఇన్ చేయవచ్చు.',
    'auth.or_continue_with': 'లేదా దీని ద్వారా కొనసాగించండి',
    'auth.google_signin': 'Google తో సైన్ ఇన్',
    'auth.phone_signin': 'ఫోన్ తో సైన్ ఇన్',
    'auth.terms': 'కొనసాగించడం ద్వారా, మీరు మా సేవా నిబంధనలు మరియు గోప్యతా విధానానికి అంగీకరిస్తారు',
    'common.select_language': 'భాష ఎంచుకోండి',
    'common.continue': 'కొనసాగించు',
    'common.cancel': 'రద్దు చేయి',
    'common.save': 'సేవ్',
    'common.loading': 'దయచేసి వేచి ఉండండి...',
    'common.signout': 'సైన్ అవుట్',
    'common.profile': 'ప్రొఫైల్',
    'common.back': 'పాత్ర ఎంపికకు తిరిగి వెళ్ళు',
    'dashboard.title': 'డ్యాష్‌బోర్డ్',
    'dashboard.welcome': 'తిరిగి రావడానికి స్వాగతం',
    'dashboard.active_crops': 'క్రియాశీల పంటలు',
    'dashboard.total_area': 'మొత్తం విస్తీర్ణం',
    'dashboard.active_sensors': 'క్రియాశీల సెన్సార్లు',
    'dashboard.upcoming_tasks': 'రాబోయే పనులు',
    'nav.dashboard': 'డ్యాష్‌బోర్డ్',
    'nav.crops': 'నా పంటలు',
    'nav.advisory': 'సలహా',
    'nav.weather': 'వాతావరణం',
    'nav.sensors': 'సెన్సార్లు',
    'nav.fieldmap': 'పొలం మ్యాప్',
    'nav.merchants': 'వ్యాపారులు',
    'nav.polls': 'పోల్స్',
    'nav.schemes': 'ప్రభుత్వ పథకాలు',
    'hero.title': 'స్మార్ట్ క్రాప్ అడ్వైజరీ',
    'hero.subtitle': 'సిస్టమ్',
    'hero.description': 'AI-ఆధారిత సిఫార్సులు, రియల్-టైమ్ మానిటరింగ్, మరియు నిపుణుల మార్గదర్శకత్వంతో మీ వ్యవసాయంలో విప్లవం తీసుకురండి.',
    'hero.cta': 'ఉచితంగా ప్రారంభించండి',
    'hero.demo': 'డెమో చూడండి',
    'features.title': 'స్మార్ట్ వ్యవసాయానికి',
    'features.highlight': 'అంతా',
    'features.description': 'డేటా-ఆధారిత నిర్ణయాలు తీసుకోవడంలో సహాయపడే సమగ్ర సాధనాలు మరియు అంతర్దృష్టులు',
    'ai.placeholder': 'పంటలు, వాతావరణం, వ్యవసాయ చిట్కాల గురించి అడగండి...',
    'ai.title': 'AI వ్యవసాయ సహాయకుడు',
    'ai.greeting': 'నమస్కారం! 🙏 నేను మీ AI వ్యవసాయ సహాయకుడిని. పంటలు, వాతావరణం, నేల, లేదా వ్యవసాయ పద్ధతుల గురించి ఏదైనా అడగండి!',
  },
  ta: {
    'auth.welcome': 'ஸ்மார்ட் க்ராப் அட்வைசரிக்கு வரவேற்கிறோம்',
    'auth.signin_farmer': 'விவசாயியாக உள்நுழைக',
    'auth.signin_merchant': 'வணிகராக உள்நுழைக',
    'auth.signin_expert': 'நிபுணராக உள்நுழைக',
    'auth.signin_admin': 'நிர்வாகியாக உள்நுழைக',
    'auth.farmer_desc': 'பயிர்களை நிர்வகிக்கவும், AI பரிந்துரைகள் பெறவும், வணிகர்களுடன் இணையவும்',
    'auth.merchant_desc': 'விவசாயிகளுடன் இணையவும், கொள்முதல் நிர்வகிக்கவும், பயிர் விலைகள் நிர்ணயிக்கவும்',
    'auth.expert_desc': 'ஆலோசனை சேவைகள் வழங்கவும், விவசாய நிபுணத்துவத்தை பகிரவும்',
    'auth.admin_desc': 'அமைப்பை நிர்வகிக்கவும், அனைத்து செயல்பாடுகள் மற்றும் பயனர்களை கண்காணிக்கவும்',
    'auth.email': 'மின்னஞ்சல்',
    'auth.password': 'கடவுச்சொல்',
    'auth.signin': 'உள்நுழைக',
    'auth.signup': 'கணக்கு உருவாக்க',
    'auth.signin_desc': 'உங்கள் டாஷ்போர்டை அணுக உங்கள் விவரங்களை உள்ளிடவும்',
    'auth.signup_desc': 'தொடங்க புதிய கணக்கை உருவாக்கவும்',
    'auth.fullname': 'முழு பெயர்',
    'auth.role': 'பங்கு',
    'auth.phone': 'தொலைபேசி எண்',
    'auth.location': 'இடம்',
    'auth.enter_email': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    'auth.enter_password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'auth.enter_name': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'auth.enter_phone': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
    'auth.enter_location': 'உங்கள் இடத்தை உள்ளிடவும்',
    'auth.no_account': 'கணக்கு இல்லையா? பதிவு செய்யவும்',
    'auth.have_account': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையவும்',
    'auth.forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'auth.login_success': 'மீண்டும் வரவேற்கிறோம்!',
    'auth.logged_in_as': 'உள்நுழைந்துள்ளீர்கள்',
    'auth.login_failed': 'உள்நுழைவு தோல்வி',
    'auth.invalid_credentials': 'இந்த பங்குக்கு தவறான மின்னஞ்சல் அல்லது கடவுச்சொல். முதலில் பதிவு செய்யவும்.',
    'auth.weak_password': 'பலவீனமான கடவுச்சொல்',
    'auth.password_min': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.',
    'auth.user_exists': 'பயனர் உள்ளார்',
    'auth.already_registered': 'இந்த மின்னஞ்சல் இந்த பங்குக்கு ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது. உள்நுழையவும்.',
    'auth.signup_success': 'கணக்கு உருவாக்கப்பட்டது!',
    'auth.now_login': 'இப்போது உங்கள் விவரங்களுடன் உள்நுழையலாம்.',
    'auth.or_continue_with': 'அல்லது இதன் மூலம் தொடரவும்',
    'auth.google_signin': 'Google மூலம் உள்நுழைக',
    'auth.phone_signin': 'தொலைபேசி மூலம் உள்நுழைக',
    'auth.terms': 'தொடர்வதன் மூலம், நீங்கள் எங்கள் சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஒப்புக்கொள்கிறீர்கள்',
    'common.select_language': 'மொழி தேர்வு செய்க',
    'common.continue': 'தொடர்க',
    'common.cancel': 'ரத்து செய்',
    'common.save': 'சேமி',
    'common.loading': 'காத்திருக்கவும்...',
    'common.signout': 'வெளியேறு',
    'common.profile': 'சுயவிவரம்',
    'common.back': 'பங்கு தேர்வுக்கு திரும்பு',
    'dashboard.title': 'டாஷ்போர்டு',
    'dashboard.welcome': 'மீண்டும் வரவேற்கிறோம்',
    'dashboard.active_crops': 'செயலில் உள்ள பயிர்கள்',
    'dashboard.total_area': 'மொத்த பரப்பு',
    'dashboard.active_sensors': 'செயலில் உள்ள சென்சார்கள்',
    'dashboard.upcoming_tasks': 'வரவிருக்கும் பணிகள்',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.crops': 'எனது பயிர்கள்',
    'nav.advisory': 'ஆலோசனை',
    'nav.weather': 'வானிலை',
    'nav.sensors': 'சென்சார்கள்',
    'nav.fieldmap': 'வயல் வரைபடம்',
    'nav.merchants': 'வணிகர்கள்',
    'nav.polls': 'வாக்கெடுப்பு',
    'nav.schemes': 'அரசு திட்டங்கள்',
    'hero.title': 'ஸ்மார்ட் க்ராப் அட்வைசரி',
    'hero.subtitle': 'சிஸ்டம்',
    'hero.description': 'AI-இயக்கப்படும் பரிந்துரைகள், நிகழ்நேர கண்காணிப்பு, மற்றும் நிபுணர் வழிகாட்டுதலுடன் உங்கள் விவசாயத்தில் புரட்சி செய்யுங்கள்.',
    'hero.cta': 'இலவசமாக தொடங்குங்கள்',
    'hero.demo': 'டெமோ பாருங்கள்',
    'features.title': 'ஸ்மார்ட் விவசாயத்திற்கு',
    'features.highlight': 'எல்லாம்',
    'features.description': 'தரவு அடிப்படையிலான முடிவுகளை எடுக்க உதவும் விரிவான கருவிகள் மற்றும் நுண்ணறிவுகள்',
    'ai.placeholder': 'பயிர்கள், வானிலை, விவசாய குறிப்புகள் பற்றி கேளுங்கள்...',
    'ai.title': 'AI விவசாய உதவியாளர்',
    'ai.greeting': 'வணக்கம்! 🙏 நான் உங்கள் AI விவசாய உதவியாளர். பயிர்கள், வானிலை, மண், அல்லது விவசாய நுட்பங்கள் பற்றி எதையும் கேளுங்கள்!',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    const translation = translations[language];
    return translation[key] || translations['en'][key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
