// Firebase configuration
// This file is automatically generated. Do not edit it directly.

import { initializeApp } from "firebase/app";
import { getAuth, RecaptchaVerifier, signInWithPhoneNumber, ConfirmationResult, User, onAuthStateChanged as firebaseOnAuthStateChanged, PhoneAuthProvider, signInWithCredential } from "firebase/auth";

const firebaseConfig = {
  apiKey: "AIzaSyD4sPDW7IzQk63CLjOlXf_QA_lP-BINvMQ",
  authDomain: "farmintellect65.firebaseapp.com",
  projectId: "farmintellect65",
  storageBucket: "farmintellect65.firebasestorage.app",
  messagingSenderId: "960040509665",
  appId: "1:960040509665:web:b5fe823a0a1b2cf18817a0",
  measurementId: "G-FG6QGRRP9W"
};

// Initialize Firebase with error handling
let app: any = null;
let auth: any = null;
let confirmationResultGlobal: ConfirmationResult | null = null;
let recaptchaVerifierGlobal: RecaptchaVerifier | null = null;
let recaptchaContainerId: string | null = null;
type OTPError = Error & { code?: string };
const createOTPError = (messageKey: string, code: string): OTPError => {
  const error: OTPError = new Error(messageKey);
  error.code = code;
  return error;
};
const clearVerificationState = () => {
  confirmationResultGlobal = null;
  sessionStorage.removeItem("firebase_verification_id");
  if (recaptchaVerifierGlobal) {
    recaptchaVerifierGlobal.clear();
    recaptchaVerifierGlobal = null;
  }
  recaptchaContainerId = null;
};

try {
  app = initializeApp(firebaseConfig);
  auth = getAuth(app);
} catch (error) {
  console.error("Firebase initialization error:", error);
}

// Firebase Authentication Helper
export const FirebaseAuth = {
  // Check if Firebase is initialized
  isAvailable: (): boolean => {
    return auth !== null;
  },

  // Initialize Recaptcha
  initRecaptcha: (containerId: string): RecaptchaVerifier | null => {
    if (!auth) return null;
    try {
      if (recaptchaVerifierGlobal && recaptchaContainerId === containerId) {
        return recaptchaVerifierGlobal;
      }

      if (recaptchaVerifierGlobal) {
        recaptchaVerifierGlobal.clear();
        recaptchaVerifierGlobal = null;
      }

      recaptchaContainerId = containerId;
      const recaptchaVerifier = new RecaptchaVerifier(auth, containerId, {
        size: 'invisible',
        callback: () => {},
        'expired-callback': () => {}
      });
      recaptchaVerifier.render();
      recaptchaVerifierGlobal = recaptchaVerifier;
      return recaptchaVerifier;
    } catch (error) {
      console.error("Recaptcha error:", error);
      return null;
    }
  },

  // Send OTP to phone number
  sendOTP: async (phoneNumber: string, containerId: string): Promise<ConfirmationResult> => {
    if (!auth) {
      throw createOTPError("auth.otp_service_unavailable", "auth/unavailable");
    }

    try {
      let recaptchaContainer = document.getElementById(containerId);
      if (!recaptchaContainer) {
        recaptchaContainer = document.createElement("div");
        recaptchaContainer.id = containerId;
        recaptchaContainer.style.display = "none";
        document.body.appendChild(recaptchaContainer);
      }

      const recaptchaVerifier = FirebaseAuth.initRecaptcha(containerId);
      if (!recaptchaVerifier) {
        throw new Error("Failed to initialize reCAPTCHA");
      }
      
      const result = await signInWithPhoneNumber(auth, phoneNumber, recaptchaVerifier);
      confirmationResultGlobal = result;
      sessionStorage.setItem("firebase_verification_id", result.verificationId);
      return result;
    } catch (error: any) {
      console.error("Error sending OTP:", error);
      if (recaptchaVerifierGlobal) {
        recaptchaVerifierGlobal.clear();
        recaptchaVerifierGlobal = null;
      }
      throw error;
    }
  },

  // Verify OTP code
  verifyOTP: async (otpCode: string): Promise<User | null> => {
    if (!auth) {
      throw createOTPError("auth.otp_service_unavailable", "auth/unavailable");
    }

    try {
      const verificationId = sessionStorage.getItem("firebase_verification_id");

      if (confirmationResultGlobal) {
        try {
          const result = await confirmationResultGlobal.confirm(otpCode);
          clearVerificationState();
          return result.user;
        } catch (error) {
          if (!verificationId) {
            throw error;
          }

          try {
            const credential = PhoneAuthProvider.credential(verificationId, otpCode);
            const result = await signInWithCredential(auth, credential);
            clearVerificationState();
            return result.user;
          } catch (fallbackError) {
            const fallbackCode = (fallbackError as { code?: string })?.code;
            const fallbackMessage = fallbackError instanceof Error
              ? fallbackError.message
              : "auth.otp_verify_failed";
            throw createOTPError(fallbackMessage, fallbackCode ?? "auth/otp-fallback");
          }
        }
      }

      if (!verificationId) {
        throw createOTPError("auth.otp_session_expired", "auth/missing-confirmation");
      }

      const credential = PhoneAuthProvider.credential(verificationId, otpCode);
      const result = await signInWithCredential(auth, credential);
      clearVerificationState();
      return result.user;
    } catch (error: unknown) {
      const parsedError = error as { code?: string };
      if (parsedError?.code === "auth/code-expired" || parsedError?.code === "auth/session-expired") {
        clearVerificationState();
      }
      console.error("Error verifying OTP:", error);
      throw error;
    }
  },

  // Get current user
  getCurrentUser: (): User | null => {
    return auth?.currentUser || null;
  },

  // Sign out
  signOut: async (): Promise<void> => {
    if (auth) {
      const { signOut: firebaseSignOut } = await import("firebase/auth");
      await firebaseSignOut(auth);
    }
    clearVerificationState();
    localStorage.removeItem("firebase_confirmation");
    localStorage.removeItem("farmer_user");
  },

  // Listen to auth state changes
  onAuthStateChanged: (callback: (user: User | null) => void): (() => void) => {
    if (!auth) {
      // Return a no-op unsubscribe if auth is not available
      return () => {};
    }
    return firebaseOnAuthStateChanged(auth, callback);
  }
};

export { auth, app };
export default app;
