// Firebase configuration
// This file is automatically generated. Do not edit it directly.

import { initializeApp } from "firebase/app";
import { getAuth, RecaptchaVerifier, signInWithPhoneNumber, ConfirmationResult, User, onAuthStateChanged as firebaseOnAuthStateChanged, PhoneAuthProvider, signInWithCredential } from "firebase/auth";

const firebaseConfig = {
  apiKey: "AIzaSyD4sPDW7IzQk63CLjOlXf_QA_lP-BINvMQ",
  authDomain: "farmintellect65.firebaseapp.com",
  projectId: "farmintellect65",
  storageBucket: "farmintellect65.firebasestorage.app",
  messagingSenderId: "960040509665",
  appId: "1:960040509665:web:b5fe823a0a1b2cf18817a0",
  measurementId: "G-FG6QGRRP9W"
};

// Initialize Firebase with error handling
let app: any = null;
let auth: any = null;
let confirmationResultGlobal: ConfirmationResult | null = null;
let recaptchaVerifierGlobal: RecaptchaVerifier | null = null;
let recaptchaContainerId: string | null = null;

try {
  app = initializeApp(firebaseConfig);
  auth = getAuth(app);
} catch (error) {
  console.error("Firebase initialization error:", error);
}

// Firebase Authentication Helper
export const FirebaseAuth = {
  // Check if Firebase is initialized
  isAvailable: (): boolean => {
    return auth !== null;
  },

  // Initialize Recaptcha
  initRecaptcha: (containerId: string): RecaptchaVerifier | null => {
    if (!auth) return null;
    try {
      if (recaptchaVerifierGlobal && recaptchaContainerId === containerId) {
        return recaptchaVerifierGlobal;
      }

      if (recaptchaVerifierGlobal) {
        recaptchaVerifierGlobal.clear();
        recaptchaVerifierGlobal = null;
      }

      recaptchaContainerId = containerId;
      const recaptchaVerifier = new RecaptchaVerifier(auth, containerId, {
        size: 'invisible',
        callback: () => {},
        'expired-callback': () => {}
      });
      recaptchaVerifier.render();
      recaptchaVerifierGlobal = recaptchaVerifier;
      return recaptchaVerifier;
    } catch (error) {
      console.error("Recaptcha error:", error);
      return null;
    }
  },

  // Send OTP to phone number
  sendOTP: async (phoneNumber: string, containerId: string): Promise<ConfirmationResult> => {
    if (!auth) {
      throw new Error("Firebase is not available. Please refresh the page.");
    }

    try {
      let recaptchaContainer = document.getElementById(containerId);
      if (!recaptchaContainer) {
        recaptchaContainer = document.createElement("div");
        recaptchaContainer.id = containerId;
        recaptchaContainer.style.display = "none";
        document.body.appendChild(recaptchaContainer);
      }

      const recaptchaVerifier = FirebaseAuth.initRecaptcha(containerId);
      if (!recaptchaVerifier) {
        throw new Error("Failed to initialize reCAPTCHA");
      }
      
      const result = await signInWithPhoneNumber(auth, phoneNumber, recaptchaVerifier);
      confirmationResultGlobal = result;
      localStorage.setItem("firebase_verification_id", result.verificationId);
      localStorage.setItem("firebase_phone_number", phoneNumber);
      return result;
    } catch (error: any) {
      console.error("Error sending OTP:", error);
      if (recaptchaVerifierGlobal) {
        recaptchaVerifierGlobal.clear();
        recaptchaVerifierGlobal = null;
      }
      throw error;
    }
  },

  // Verify OTP code
  verifyOTP: async (otpCode: string): Promise<User | null> => {
    if (!auth) {
      throw new Error("Firebase is not available. Please refresh the page.");
    }

    try {
      if (confirmationResultGlobal) {
        const result = await confirmationResultGlobal.confirm(otpCode);
        confirmationResultGlobal = null;
        localStorage.removeItem("firebase_verification_id");
        localStorage.removeItem("firebase_phone_number");
        return result.user;
      }

      const verificationId = localStorage.getItem("firebase_verification_id");
      if (!verificationId) {
        throw new Error("No confirmation result found. Please request a new OTP.");
      }

      const credential = PhoneAuthProvider.credential(verificationId, otpCode);
      const result = await signInWithCredential(auth, credential);
      localStorage.removeItem("firebase_verification_id");
      localStorage.removeItem("firebase_phone_number");
      return result.user;
    } catch (error) {
      console.error("Error verifying OTP:", error);
      throw error;
    }
  },

  // Get current user
  getCurrentUser: (): User | null => {
    return auth?.currentUser || null;
  },

  // Sign out
  signOut: async (): Promise<void> => {
    if (auth) {
      const { signOut: firebaseSignOut } = await import("firebase/auth");
      await firebaseSignOut(auth);
    }
    confirmationResultGlobal = null;
    if (recaptchaVerifierGlobal) {
      recaptchaVerifierGlobal.clear();
      recaptchaVerifierGlobal = null;
    }
    recaptchaContainerId = null;
    localStorage.removeItem("firebase_confirmation");
    localStorage.removeItem("farmer_user");
    localStorage.removeItem("firebase_verification_id");
    localStorage.removeItem("firebase_phone_number");
  },

  // Listen to auth state changes
  onAuthStateChanged: (callback: (user: User | null) => void): (() => void) => {
    if (!auth) {
      // Return a no-op unsubscribe if auth is not available
      return () => {};
    }
    return firebaseOnAuthStateChanged(auth, callback);
  }
};

export { auth, app };
export default app;
